version: 0.0
os: linux
files:
  - source: /magento
    destination: /var/www/magento
permissions:
  - object: /var/www/magento
    pattern: "**"
    owner: apache
    group: apache
    mode: 664
    type:
      - file
  - object: /var/www/magento
    pattern: "**"
    owner: apache
    group: apache
    mode: 2775
    type:
      - directory
